/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Enum.State;
import static GUI.GUI_Start.BLUE_COLOR;
import static GUI.GUI_Start.GREEN_COLOR;
import static GUI.GUI_Start.RED_COLOR;
import static GUI.GUI_Start.actualColor;
import User.Voter;
import java.awt.CardLayout;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rebec
 */
public class GUI_Voter extends javax.swing.JFrame {

    private CardLayout cards;
    private Voter admin ; 
    private String [][] infosCandidate ;
    private int cursorCandidate ; 
    private FileManager f;
    
    /**
     * Creates new form GUI_Voter
     * @param admin
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public GUI_Voter(Voter admin) throws SQLException, ClassNotFoundException {
        this.admin = admin ; 
        admin.setDataController();
        this.infosCandidate = null ; 
        this.cursorCandidate = 0 ; 
        initComponents();
        
        if(admin.getVotedFor())
        {
            answerVote.setText("You have already voted.");
            answerVote.setForeground(GREEN_COLOR);
        }
        
        setLocationRelativeTo(null);
        setVisible(true);
        //Setting State values in the combo boxes
        for (State s : State.values())
            stateComboBox.addItem(s.toString());
        stateComboBox.setSelectedItem(admin.getState());
        cards = (CardLayout)mainPanel.getLayout();
        
        if (admin.isElectionOpen())
        {
            electionText.setText("Election is open");
            electionText.setForeground(GREEN_COLOR);
        }
        else
        {
            electionText.setText("Election is closed");
            electionText.setForeground(RED_COLOR);
        }  
        
        //File Manager to save users preferences
        try {
            f=new FileManager(); 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_Official.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void embeddedMain() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsPopUp = new javax.swing.JPopupMenu();
        redOption = new javax.swing.JMenuItem();
        greenOption = new javax.swing.JMenuItem();
        blueOption = new javax.swing.JMenuItem();
        leftPanel = new javax.swing.JPanel();
        SetingColorButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        main_menu = new javax.swing.JPanel();
        colorPanel = new javax.swing.JPanel();
        mainMenuText = new javax.swing.JLabel();
        questionVote = new javax.swing.JLabel();
        answerVote = new javax.swing.JLabel();
        viewCandidateButton = new javax.swing.JButton();
        mainMenuText1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        republicText = new javax.swing.JLabel();
        electionText = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        editProfileFirstName = new javax.swing.JTextField();
        editProfileLastName = new javax.swing.JTextField();
        editVoterDate = new javax.swing.JFormattedTextField();
        editVoterEmail = new javax.swing.JTextField();
        editVoterPassword = new javax.swing.JTextField();
        stateComboBox = new javax.swing.JComboBox<>();
        mainMenuText2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        viewCandidatePanel = new javax.swing.JPanel();
        nameCandidateLabel = new javax.swing.JLabel();
        partyCandidateText = new javax.swing.JLabel();
        descriptionCandidateText = new javax.swing.JLabel();
        voteForButton = new javax.swing.JButton();
        preCandidateButton = new javax.swing.JButton();
        nextCandidateButton = new javax.swing.JButton();
        goBackMenuButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        settingsPopUp.setMaximumSize(new java.awt.Dimension(32773, 98307));
        settingsPopUp.setPreferredSize(new java.awt.Dimension(200, 100));
        settingsPopUp.setRequestFocusEnabled(false);

        redOption.setText("Set color to red");
        redOption.setPreferredSize(new java.awt.Dimension(313, 46));
        redOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(redOption);

        greenOption.setText("Set color to green");
        greenOption.setPreferredSize(new java.awt.Dimension(313, 46));
        greenOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(greenOption);

        blueOption.setText("Set color to blue");
        blueOption.setPreferredSize(new java.awt.Dimension(313, 46));
        blueOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(blueOption);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election Simulator");
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));

        leftPanel.setBackground(new java.awt.Color(0, 102, 130));
        leftPanel.setMaximumSize(new java.awt.Dimension(180, 0));
        leftPanel.setMinimumSize(new java.awt.Dimension(180, 0));
        leftPanel.setPreferredSize(new java.awt.Dimension(180, 0));

        SetingColorButton.setBackground(new java.awt.Color(255, 255, 255));
        SetingColorButton.setForeground(new java.awt.Color(255, 255, 255));
        SetingColorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/gearIcon.png"))); // NOI18N
        SetingColorButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        SetingColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetingColorButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logoutIcon.png"))); // NOI18N
        exitButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/userIcon.png"))); // NOI18N
        profileButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(profileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(SetingColorButton)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SetingColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        mainPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        mainPanel.setPreferredSize(new java.awt.Dimension(623, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        main_menu.setBackground(new java.awt.Color(255, 255, 255));

        colorPanel.setBackground(actualColor   );

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        mainMenuText.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuText.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        mainMenuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuText.setText("Welcome " + admin.getFirstName() + " " + admin.getLastName() + " to the voter center.");

        questionVote.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        questionVote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionVote.setText("Have you voted ? ");

        answerVote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answerVote.setForeground(new java.awt.Color(170, 40, 50));
        answerVote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerVote.setText("Not yet ! ");

        viewCandidateButton.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        viewCandidateButton.setText("View candidates and vote");
        viewCandidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCandidateButtonActionPerformed(evt);
            }
        });

        mainMenuText1.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuText1.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        mainMenuText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuText1.setText("Voter Main Menu");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/index.png"))); // NOI18N

        republicText.setBackground(new java.awt.Color(255, 255, 255));
        republicText.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        republicText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        republicText.setText("Republic of Moebus");

        electionText.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        electionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        electionText.setText("Election Opened");

        javax.swing.GroupLayout main_menuLayout = new javax.swing.GroupLayout(main_menu);
        main_menu.setLayout(main_menuLayout);
        main_menuLayout.setHorizontalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainMenuText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(republicText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(electionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_menuLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(main_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewCandidateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(answerVote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(questionVote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        main_menuLayout.setVerticalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainMenuText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(republicText)
                .addGap(18, 18, 18)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(electionText)
                .addGap(109, 109, 109)
                .addComponent(questionVote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerVote)
                .addGap(18, 18, 18)
                .addComponent(viewCandidateButton)
                .addGap(56, 56, 56))
        );

        mainPanel.add(main_menu, "mainMenu");

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));

        editProfileFirstName.setText(admin.getFirstName());
        editProfileFirstName.setBorder(javax.swing.BorderFactory.createTitledBorder("First Name"));
        editProfileFirstName.setEnabled(false);
        editProfileFirstName.setMinimumSize(new java.awt.Dimension(12, 74));
        editProfileFirstName.setPreferredSize(new java.awt.Dimension(12, 74));

        editProfileLastName.setText(admin.getLastName());
        editProfileLastName.setBorder(javax.swing.BorderFactory.createTitledBorder("Last Name"));
        editProfileLastName.setEnabled(false);
        editProfileLastName.setMinimumSize(new java.awt.Dimension(12, 74));
        editProfileLastName.setPreferredSize(new java.awt.Dimension(12, 74));

        editVoterDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date of birth"));
        editVoterDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        editVoterDate.setText(admin.getDOB());
        editVoterDate.setEnabled(false);
        editVoterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVoterDateActionPerformed(evt);
            }
        });

        editVoterEmail.setText(admin.getEmail());
        editVoterEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Email"));

        editVoterPassword.setText(admin.getPassword());
        editVoterPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password"));

        stateComboBox.setBorder(null);
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });

        mainMenuText2.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuText2.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        mainMenuText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuText2.setText("Profile");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("If you want to modify your First Name, Last Name and date of birth, please contact an official.");

        saveButton.setText("Save Modifications");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editVoterEmail)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanelLayout.createSequentialGroup()
                                .addComponent(editProfileFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(editProfileLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editVoterDate, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(editVoterPassword)
                            .addComponent(stateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(goBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addGap(20, 20, 20))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(mainMenuText2)
                .addGap(36, 36, 36)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProfileFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProfileLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editVoterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editVoterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editVoterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 389, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(goBackButton)
                            .addComponent(saveButton))
                        .addContainerGap())))
        );

        mainPanel.add(profilePanel, "profile");

        viewCandidatePanel.setBackground(new java.awt.Color(255, 255, 255));

        nameCandidateLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameCandidateLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        nameCandidateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameCandidateLabel.setText("Name");

        partyCandidateText.setBackground(new java.awt.Color(255, 255, 255));
        partyCandidateText.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        partyCandidateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        partyCandidateText.setText("Party");

        descriptionCandidateText.setText("Description");
        descriptionCandidateText.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        voteForButton.setBackground(new java.awt.Color(255, 255, 255));
        voteForButton.setText("Vote for this candidate");
        voteForButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteForButtonActionPerformed(evt);
            }
        });

        preCandidateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/leftArrowIcon.png"))); // NOI18N
        preCandidateButton.setContentAreaFilled(false);
        preCandidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preCandidateButtonActionPerformed(evt);
            }
        });

        nextCandidateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rightArrowIcon.png"))); // NOI18N
        nextCandidateButton.setContentAreaFilled(false);
        nextCandidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCandidateButtonActionPerformed(evt);
            }
        });

        goBackMenuButton.setText("Go Back");
        goBackMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackMenuButtonActionPerformed(evt);
            }
        });

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout viewCandidatePanelLayout = new javax.swing.GroupLayout(viewCandidatePanel);
        viewCandidatePanel.setLayout(viewCandidatePanelLayout);
        viewCandidatePanelLayout.setHorizontalGroup(
            viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameCandidateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addComponent(partyCandidateText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(viewCandidatePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionCandidateText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(viewCandidatePanelLayout.createSequentialGroup()
                        .addGroup(viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goBackMenuButton)
                            .addComponent(preCandidateButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voteForButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextCandidateButton)))
                .addGap(20, 20, 20))
        );
        viewCandidatePanelLayout.setVerticalGroup(
            viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCandidatePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nameCandidateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partyCandidateText)
                .addGap(18, 18, 18)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descriptionCandidateText)
                .addGap(18, 18, 18)
                .addGroup(viewCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preCandidateButton)
                    .addComponent(voteForButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextCandidateButton))
                .addGap(20, 20, 20)
                .addComponent(goBackMenuButton)
                .addContainerGap())
        );

        mainPanel.add(viewCandidatePanel, "viewCandidate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
        GUI_Start mainMenu;
        try {
            mainMenu = new GUI_Start();
            mainMenu.embeddedMain();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GUI_Official.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void SetingColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetingColorButtonActionPerformed
        settingsPopUp.show(this, SetingColorButton.getX(), SetingColorButton.getY()-settingsPopUp.getHeight()/2-2);
    }//GEN-LAST:event_SetingColorButtonActionPerformed

    private void redOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redOptionActionPerformed
        actualColor=RED_COLOR;
        leftPanel.setBackground(actualColor);
        colorPanel.setBackground(actualColor);
        f.saveColor(actualColor);
    }//GEN-LAST:event_redOptionActionPerformed

    private void greenOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenOptionActionPerformed
        actualColor=GREEN_COLOR;
        leftPanel.setBackground(actualColor);
        colorPanel.setBackground(actualColor);
        f.saveColor(actualColor);
    }//GEN-LAST:event_greenOptionActionPerformed

    private void blueOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueOptionActionPerformed
        actualColor=BLUE_COLOR;
        leftPanel.setBackground(actualColor);
        colorPanel.setBackground(actualColor);
        f.saveColor(actualColor);
    }//GEN-LAST:event_blueOptionActionPerformed

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void editVoterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVoterDateActionPerformed
        
    }//GEN-LAST:event_editVoterDateActionPerformed

    private void viewCardsCandidate()
    {
        if(cursorCandidate == 0 )
            preCandidateButton.setEnabled(false);
        else 
            preCandidateButton.setEnabled(true);
        
        if(cursorCandidate == infosCandidate.length - 1 )
            nextCandidateButton.setEnabled(false);
        else 
            nextCandidateButton.setEnabled(true);
        
        if(admin.getVotedFor())
            voteForButton.setEnabled(false);
        else 
            voteForButton.setEnabled(true);
        
        byte[] myImage = admin.getImage(infosCandidate[cursorCandidate][0]);
        if (myImage!=null)
        {
            ImageIcon image = new ImageIcon(myImage);
            imageLabel.setText("");
            imageLabel.setIcon(image);
        }
        else
        {
            imageLabel.setText("There is no picture available.");
            imageLabel.setIcon(null);
        }
        
        nameCandidateLabel.setText(infosCandidate[cursorCandidate][1] + " " + infosCandidate[cursorCandidate][2]); 
        partyCandidateText.setText("Party : " + infosCandidate[cursorCandidate][3]); 
        descriptionCandidateText.setText(infosCandidate[cursorCandidate][4]); 
        
        cards.show(mainPanel, "viewCandidate");
    }
    
    private void viewCandidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCandidateButtonActionPerformed
        infosCandidate = admin.getAllCandidate(); 
        if(infosCandidate != null)
            viewCardsCandidate() ;
    }//GEN-LAST:event_viewCandidateButtonActionPerformed

    
    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        cards.show(mainPanel, "profile");
    }//GEN-LAST:event_profileButtonActionPerformed

    private void nextCandidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCandidateButtonActionPerformed
        cursorCandidate ++ ; 
        viewCandidateButtonActionPerformed(evt); 
    }//GEN-LAST:event_nextCandidateButtonActionPerformed

    private void voteForButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteForButtonActionPerformed
        admin.vote(infosCandidate[cursorCandidate][0]); 
        JOptionPane.showMessageDialog(null, "Your vote was successfully taken into account" , this.getTitle(), 1 );
        if(admin.getVotedFor())
        {
            answerVote.setText("You have already voted.");
            answerVote.setForeground(GREEN_COLOR);
            voteForButton.setEnabled(false);
        }
    }//GEN-LAST:event_voteForButtonActionPerformed

    private void preCandidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preCandidateButtonActionPerformed
        cursorCandidate -- ; 
        viewCandidateButtonActionPerformed(evt); 
    }//GEN-LAST:event_preCandidateButtonActionPerformed

    private void goBackMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackMenuButtonActionPerformed
        cards.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_goBackMenuButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (editVoterEmail.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a valid email" , this.getTitle(), 1 );
        else if (editVoterPassword.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a valid password" , this.getTitle(), 1 );
        else{
        String [] infosModif = new String[3] ;
        infosModif[0] = (String)stateComboBox.getModel().getSelectedItem();
        infosModif[1] = editVoterEmail.getText();
        infosModif[2] = editVoterPassword.getText();
        if(admin.updateProfile(infosModif))
        JOptionPane.showMessageDialog(null, "Informations successfully edited" , this.getTitle(), 1 );
        else
        JOptionPane.showMessageDialog(null, "A problem occured. Your modification was not taken into account." , this.getTitle(), 1 );
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        cards.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_goBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SetingColorButton;
    private javax.swing.JLabel answerVote;
    private javax.swing.JMenuItem blueOption;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JLabel descriptionCandidateText;
    private javax.swing.JTextField editProfileFirstName;
    private javax.swing.JTextField editProfileLastName;
    private javax.swing.JFormattedTextField editVoterDate;
    private javax.swing.JTextField editVoterEmail;
    private javax.swing.JTextField editVoterPassword;
    private javax.swing.JLabel electionText;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton goBackMenuButton;
    private javax.swing.JMenuItem greenOption;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel mainMenuText;
    private javax.swing.JLabel mainMenuText1;
    private javax.swing.JLabel mainMenuText2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel main_menu;
    private javax.swing.JLabel nameCandidateLabel;
    private javax.swing.JButton nextCandidateButton;
    private javax.swing.JLabel partyCandidateText;
    private javax.swing.JButton preCandidateButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel questionVote;
    private javax.swing.JMenuItem redOption;
    private javax.swing.JLabel republicText;
    private javax.swing.JButton saveButton;
    private javax.swing.JPopupMenu settingsPopUp;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JButton viewCandidateButton;
    private javax.swing.JPanel viewCandidatePanel;
    private javax.swing.JButton voteForButton;
    // End of variables declaration//GEN-END:variables
}
