/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electionapplication.GUI;

import electionapplication.Enum.State;
import electionapplication.User.Voter;
import electionapplication.User.Official;
import static electionapplication.ElectionApplication.convertSQLtoGregorian;
import electionapplication.Enum.Party;
import electionapplication.User.Candidate;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 * GUI used by the officials.
 * @author Keke
 */
public class GUI_Official extends javax.swing.JFrame {

    private Official admin;
    private CardLayout cards;
    private DefaultTableModel voterTableModel;
    
    public GUI_Official(Official admin) {
        
        this.admin = admin;
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
      
        for (State s : State.values())
        {
            jComboBox1.addItem(s.toString());
            jComboBox3.addItem(s.toString());
        }
        for (Party s : Party.values())
            jComboBox2.addItem(s.toString());
        
        cards = (CardLayout)mainPanel.getLayout();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsPopUp = new javax.swing.JPopupMenu();
        redOption = new javax.swing.JMenuItem();
        greenOption = new javax.swing.JMenuItem();
        blueOption = new javax.swing.JMenuItem();
        leftPanel = new javax.swing.JPanel();
        settingsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        voteStatusText = new javax.swing.JLabel();
        statusText = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        textPanel = new javax.swing.JPanel();
        mainMenuDescription = new javax.swing.JLabel();
        mainMenuText = new javax.swing.JLabel();
        addVoterPanel = new javax.swing.JPanel();
        addVoterButton = new javax.swing.JButton();
        addVoterFirstName = new javax.swing.JTextField();
        addVoterLastName = new javax.swing.JTextField();
        addVoterEmail = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        addVoterDate = new javax.swing.JFormattedTextField();
        addVoterPassword = new javax.swing.JPasswordField();
        addVoterBack = new javax.swing.JButton();
        addVoterTextPanel = new javax.swing.JPanel();
        addVoterCaption = new javax.swing.JLabel();
        addVoterText = new javax.swing.JLabel();
        addCandidatePanel = new javax.swing.JPanel();
        addCandidateButton = new javax.swing.JButton();
        addCandidateFirstName = new javax.swing.JTextField();
        addCandidateLastName = new javax.swing.JTextField();
        addCandidateEmail = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        addCandidateDate = new javax.swing.JFormattedTextField();
        addCandidatePassword = new javax.swing.JPasswordField();
        addCandidateDescription = new javax.swing.JTextField();
        addCandidateBack = new javax.swing.JButton();
        addCandidateTextPanel = new javax.swing.JPanel();
        addCandidateText = new javax.swing.JLabel();
        addCandidateCaption = new javax.swing.JLabel();
        editVotersPanel = new javax.swing.JPanel();
        editVotersBack = new javax.swing.JButton();
        editVotersScrollPanel = new javax.swing.JScrollPane();
        editVotersTable = new javax.swing.JTable();
        editVotersEdit = new javax.swing.JButton();
        editVotersDelete = new javax.swing.JButton();
        editVotersTextPanel = new javax.swing.JPanel();
        editVotersText = new javax.swing.JLabel();
        editVotersCaption = new javax.swing.JLabel();
        editVotersEditPanel = new javax.swing.JPanel();
        editVotersEditOK = new javax.swing.JButton();
        editVoterFirstName = new javax.swing.JTextField();
        editVoterLastName = new javax.swing.JTextField();
        editVoterEmail = new javax.swing.JTextField();
        editVoterDate = new javax.swing.JFormattedTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        editVoterPassword = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        newMenu = new javax.swing.JMenu();
        newMenuVoter = new javax.swing.JMenuItem();
        newMenuCandidate = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editMenuVoter = new javax.swing.JMenuItem();
        editMenuCandidate = new javax.swing.JMenuItem();

        settingsPopUp.setPreferredSize(new java.awt.Dimension(200, 100));

        redOption.setText("Set Color to Red");
        redOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(redOption);

        greenOption.setText("Set Color to Green");
        greenOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(greenOption);

        blueOption.setText("Set Color to Blue");
        blueOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(blueOption);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election Simulator");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        leftPanel.setBackground(new java.awt.Color(0, 102, 130));
        leftPanel.setMaximumSize(new java.awt.Dimension(180, 0));
        leftPanel.setMinimumSize(new java.awt.Dimension(180, 0));
        leftPanel.setPreferredSize(new java.awt.Dimension(180, 0));

        settingsButton.setBackground(new java.awt.Color(255, 255, 255));
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionapplication/GUI/gearIcon.png"))); // NOI18N
        settingsButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionapplication/GUI/logoutIcon.png"))); // NOI18N
        exitButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(623, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setFocusTraversalPolicyProvider(true);

        voteStatusText.setBackground(new java.awt.Color(255, 255, 255));
        voteStatusText.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        voteStatusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voteStatusText.setText("Vote Status :");

        statusText.setBackground(new java.awt.Color(255, 255, 255));
        statusText.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        statusText.setForeground(new java.awt.Color(0, 185, 16));
        statusText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusText.setText("Active");

        startButton.setText("Start");

        pauseButton.setText("Pause");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        textPanel.setBackground(new java.awt.Color(255, 255, 255));

        mainMenuDescription.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuDescription.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        mainMenuDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuDescription.setText("Welcome to the admin center");

        mainMenuText.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuText.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        mainMenuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuText.setText("Official Main Menu");

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuText, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addComponent(mainMenuDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addComponent(mainMenuText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuDescription)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addComponent(voteStatusText)
                        .addGap(62, 62, 62)
                        .addComponent(statusText)))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voteStatusText)
                    .addComponent(statusText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
        );

        mainPanel.add(mainMenu, "mainMenu");

        addVoterPanel.setBackground(new java.awt.Color(255, 255, 255));

        addVoterButton.setText("Add");
        addVoterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoterButtonActionPerformed(evt);
            }
        });

        addVoterFirstName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "First Name"));
        addVoterFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoterFirstNameActionPerformed(evt);
            }
        });

        addVoterLastName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Last Name"));

        addVoterEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Email"));

        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        addVoterDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date of birth"));
        addVoterDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        addVoterDate.setText("yyyy-mm-dd");
        addVoterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoterDateActionPerformed(evt);
            }
        });

        addVoterPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password"));

        addVoterBack.setText("Go back");
        addVoterBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoterBackActionPerformed(evt);
            }
        });

        addVoterTextPanel.setBackground(new java.awt.Color(255, 255, 255));

        addVoterCaption.setBackground(new java.awt.Color(255, 255, 255));
        addVoterCaption.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        addVoterCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addVoterCaption.setText("Add a new Voter to the Database");

        addVoterText.setBackground(new java.awt.Color(255, 255, 255));
        addVoterText.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        addVoterText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addVoterText.setText("New Voter");

        javax.swing.GroupLayout addVoterTextPanelLayout = new javax.swing.GroupLayout(addVoterTextPanel);
        addVoterTextPanel.setLayout(addVoterTextPanelLayout);
        addVoterTextPanelLayout.setHorizontalGroup(
            addVoterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVoterTextPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addVoterCaption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addComponent(addVoterText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addVoterTextPanelLayout.setVerticalGroup(
            addVoterTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVoterTextPanelLayout.createSequentialGroup()
                .addComponent(addVoterText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addVoterCaption)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout addVoterPanelLayout = new javax.swing.GroupLayout(addVoterPanel);
        addVoterPanel.setLayout(addVoterPanelLayout);
        addVoterPanelLayout.setHorizontalGroup(
            addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addVoterTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addVoterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addVoterBack)
                    .addGroup(addVoterPanelLayout.createSequentialGroup()
                        .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addVoterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addVoterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addVoterPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addVoterLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addVoterDate)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVoterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addVoterButton)
                .addGap(81, 81, 81))
        );
        addVoterPanelLayout.setVerticalGroup(
            addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVoterPanelLayout.createSequentialGroup()
                .addComponent(addVoterTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVoterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVoterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVoterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addVoterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVoterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVoterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(addVoterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(addVoterBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(addVoterPanel, "addVoter");

        addCandidatePanel.setBackground(new java.awt.Color(255, 255, 255));

        addCandidateButton.setText("Add");
        addCandidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidateButtonActionPerformed(evt);
            }
        });

        addCandidateFirstName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "First Name"));
        addCandidateFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidateFirstNameActionPerformed(evt);
            }
        });

        addCandidateLastName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Last Name"));

        addCandidateEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Email"));

        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        addCandidateDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date of birth"));
        addCandidateDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        addCandidateDate.setText("yyyy-mm-dd");
        addCandidateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidateDateActionPerformed(evt);
            }
        });

        addCandidatePassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password"));

        addCandidateDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Description"));

        addCandidateBack.setText("Go back");
        addCandidateBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidateBackActionPerformed(evt);
            }
        });

        addCandidateTextPanel.setBackground(new java.awt.Color(255, 255, 255));

        addCandidateText.setBackground(new java.awt.Color(255, 255, 255));
        addCandidateText.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        addCandidateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCandidateText.setText("New Candidate");

        addCandidateCaption.setBackground(new java.awt.Color(255, 255, 255));
        addCandidateCaption.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        addCandidateCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCandidateCaption.setText("Add a new Candidate to the Database");

        javax.swing.GroupLayout addCandidateTextPanelLayout = new javax.swing.GroupLayout(addCandidateTextPanel);
        addCandidateTextPanel.setLayout(addCandidateTextPanelLayout);
        addCandidateTextPanelLayout.setHorizontalGroup(
            addCandidateTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addCandidateCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addCandidateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addCandidateTextPanelLayout.setVerticalGroup(
            addCandidateTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCandidateTextPanelLayout.createSequentialGroup()
                .addComponent(addCandidateText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCandidateCaption)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout addCandidatePanelLayout = new javax.swing.GroupLayout(addCandidatePanel);
        addCandidatePanel.setLayout(addCandidatePanelLayout);
        addCandidatePanelLayout.setHorizontalGroup(
            addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addCandidateTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addCandidatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addCandidatePanelLayout.createSequentialGroup()
                        .addComponent(addCandidateBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addCandidatePanelLayout.createSequentialGroup()
                        .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCandidatePanelLayout.createSequentialGroup()
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addCandidateFirstName)
                                    .addComponent(addCandidateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addCandidatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addCandidateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addCandidateDescription))
                        .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCandidatePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addCandidateDate)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addCandidatePanelLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(addCandidateButton)))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        addCandidatePanelLayout.setVerticalGroup(
            addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCandidatePanelLayout.createSequentialGroup()
                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCandidatePanelLayout.createSequentialGroup()
                        .addComponent(addCandidateTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCandidatePanelLayout.createSequentialGroup()
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addCandidateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addCandidateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(addCandidatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addCandidateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addCandidatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addCandidateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCandidateDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCandidatePanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(addCandidateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(addCandidateBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(addCandidatePanel, "addCandidate");

        editVotersPanel.setBackground(new java.awt.Color(255, 255, 255));

        editVotersBack.setText("Go back");
        editVotersBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVotersBackActionPerformed(evt);
            }
        });

        editVotersTable.setAutoCreateRowSorter(true);
        editVotersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        editVotersScrollPanel.setViewportView(editVotersTable);

        editVotersEdit.setText("Edit");
        editVotersEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVotersEditActionPerformed(evt);
            }
        });

        editVotersDelete.setText("Delete");
        editVotersDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVotersDeleteActionPerformed(evt);
            }
        });

        editVotersTextPanel.setBackground(new java.awt.Color(255, 255, 255));

        editVotersText.setBackground(new java.awt.Color(255, 255, 255));
        editVotersText.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        editVotersText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editVotersText.setText("Edit Voters");

        editVotersCaption.setBackground(new java.awt.Color(255, 255, 255));
        editVotersCaption.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        editVotersCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editVotersCaption.setText("Edit or delete voters by selecting one and using an option");

        javax.swing.GroupLayout editVotersTextPanelLayout = new javax.swing.GroupLayout(editVotersTextPanel);
        editVotersTextPanel.setLayout(editVotersTextPanelLayout);
        editVotersTextPanelLayout.setHorizontalGroup(
            editVotersTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editVotersTextPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(editVotersTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editVotersText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editVotersCaption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        editVotersTextPanelLayout.setVerticalGroup(
            editVotersTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editVotersTextPanelLayout.createSequentialGroup()
                .addComponent(editVotersText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editVotersCaption)
                .addGap(30, 30, 30))
        );

        editVotersEditPanel.setBackground(new java.awt.Color(255, 255, 255));

        editVotersEditOK.setText("OK");
        editVotersEditOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVotersEditOKActionPerformed(evt);
            }
        });

        editVoterFirstName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "First Name"));
        editVoterFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVoterFirstNameActionPerformed(evt);
            }
        });

        editVoterLastName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Last Name"));

        editVoterEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Email"));

        editVoterDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date of birth"));
        editVoterDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        editVoterDate.setText("yyyy-mm-dd");
        editVoterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVoterDateActionPerformed(evt);
            }
        });

        jComboBox3.setBorder(null);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        editVoterPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password"));

        javax.swing.GroupLayout editVotersEditPanelLayout = new javax.swing.GroupLayout(editVotersEditPanel);
        editVotersEditPanel.setLayout(editVotersEditPanelLayout);
        editVotersEditPanelLayout.setHorizontalGroup(
            editVotersEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editVotersEditPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(editVotersEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editVoterFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(editVoterEmail))
                .addGap(26, 26, 26)
                .addGroup(editVotersEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editVoterLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(editVoterPassword))
                .addGap(26, 26, 26)
                .addGroup(editVotersEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editVotersEditPanelLayout.createSequentialGroup()
                        .addComponent(editVoterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editVotersEditOK, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editVotersEditPanelLayout.setVerticalGroup(
            editVotersEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editVotersEditPanelLayout.createSequentialGroup()
                .addGroup(editVotersEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editVoterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editVoterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editVoterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editVotersEditOK))
                .addGap(18, 18, 18)
                .addGroup(editVotersEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editVoterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editVoterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout editVotersPanelLayout = new javax.swing.GroupLayout(editVotersPanel);
        editVotersPanel.setLayout(editVotersPanelLayout);
        editVotersPanelLayout.setHorizontalGroup(
            editVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editVotersTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(editVotersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editVotersEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editVotersPanelLayout.createSequentialGroup()
                        .addGroup(editVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editVotersBack)
                            .addGroup(editVotersPanelLayout.createSequentialGroup()
                                .addComponent(editVotersScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(editVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editVotersDelete)
                                    .addComponent(editVotersEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editVotersPanelLayout.setVerticalGroup(
            editVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editVotersPanelLayout.createSequentialGroup()
                .addComponent(editVotersTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(editVotersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editVotersPanelLayout.createSequentialGroup()
                        .addComponent(editVotersEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editVotersDelete))
                    .addComponent(editVotersScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(editVotersEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(editVotersBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(editVotersPanel, "editVoter");

        MenuBar.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        newMenu.setText("New");

        newMenuVoter.setText("Voter");
        newMenuVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuVoterActionPerformed(evt);
            }
        });
        newMenu.add(newMenuVoter);

        newMenuCandidate.setText("Candidate");
        newMenuCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuCandidateActionPerformed(evt);
            }
        });
        newMenu.add(newMenuCandidate);

        MenuBar.add(newMenu);

        editMenu.setText("Edit");

        editMenuVoter.setText("Voter");
        editMenuVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuVoterActionPerformed(evt);
            }
        });
        editMenu.add(editMenuVoter);

        editMenuCandidate.setText("Candidate");
        editMenu.add(editMenuCandidate);

        MenuBar.add(editMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
            .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMenuVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuVoterActionPerformed
        cards.show(mainPanel, "addVoter");
    }//GEN-LAST:event_newMenuVoterActionPerformed

    private void addVoterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoterButtonActionPerformed
        if (addVoterFirstName.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a first name." , this.getTitle(), 1 );
        else if (addVoterLastName.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a last name." , this.getTitle(), 1 );
        else if (addVoterEmail.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter an email adress." , this.getTitle(), 1 );
        else if (new String(addVoterPassword.getPassword()).equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a password." , this.getTitle(), 1 );
        else if (addVoterDate.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a date of birth." ,this.getTitle(), 1 );
        else if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex())==null)
            JOptionPane.showMessageDialog(null, "Please enter a state" , this.getTitle(), 1 );
        else
        {   
            if (admin.addVoter(new Voter(addVoterEmail.getText(), new String(addVoterPassword.getPassword()), convertSQLtoGregorian(addVoterDate.getText()), addVoterFirstName.getText(), addVoterLastName.getText(), jComboBox1.getItemAt(jComboBox1.getSelectedIndex())  , null)))
                JOptionPane.showMessageDialog(null, "Added successfully " + addVoterFirstName.getText() + " " + addVoterLastName.getText() + " to the database" , this.getTitle(), 1 );
            else
                JOptionPane.showMessageDialog(null, "An error occured. Email adress is already in use." , this.getTitle(), 1 );
        }
        
            
        
    }//GEN-LAST:event_addVoterButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void addVoterFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoterFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVoterFirstNameActionPerformed

    private void addVoterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoterDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVoterDateActionPerformed

    private void addCandidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidateButtonActionPerformed
        if (addCandidateFirstName.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a first name." , this.getTitle(), 1 );
        else if (addCandidateLastName.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a last name." , this.getTitle(), 1 );
        else if (addCandidateEmail.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter an email adress." , this.getTitle(), 1 );
        else if (new String(addCandidatePassword.getPassword()).equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a password." , this.getTitle(), 1 );
        else if (addCandidateDate.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a date of birth." , this.getTitle(), 1 );
        else if (jComboBox2.getItemAt(jComboBox2.getSelectedIndex())==null)
            JOptionPane.showMessageDialog(null, "Please enter a state" , this.getTitle(), 1 );
        else
        {
            if (admin.addCandidate(new Candidate(addCandidateEmail.getText(), new String(addCandidatePassword.getPassword()), 
                    convertSQLtoGregorian(addCandidateDate.getText()), addCandidateFirstName.getText(), addCandidateLastName.getText(), 
                    jComboBox2.getItemAt(jComboBox2.getSelectedIndex()), addCandidateDescription.getText())))
                JOptionPane.showMessageDialog(null, "Added successfully " + addCandidateFirstName.getText() + " " + addCandidateLastName.getText() + " to the database" , this.getTitle(), 1 );
            else
                JOptionPane.showMessageDialog(null, "An error occured. Email adress is already in use." , this.getTitle(), 1 );
        }
            
    }//GEN-LAST:event_addCandidateButtonActionPerformed

    private void addCandidateFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidateFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCandidateFirstNameActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void addCandidateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidateDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCandidateDateActionPerformed

    private void newMenuCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuCandidateActionPerformed
        cards.show(mainPanel, "addCandidate");
    }//GEN-LAST:event_newMenuCandidateActionPerformed

    private void redOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redOptionActionPerformed
        leftPanel.setBackground(new Color(170,40,50));
    }//GEN-LAST:event_redOptionActionPerformed

    private void greenOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenOptionActionPerformed
        leftPanel.setBackground(new Color(100,210,50));
    }//GEN-LAST:event_greenOptionActionPerformed

    private void blueOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueOptionActionPerformed
        leftPanel.setBackground(new Color(0,102,130));
    }//GEN-LAST:event_blueOptionActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        settingsPopUp.show(this, settingsButton.getX(), settingsButton.getY()-settingsPopUp.getHeight()/2-2);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

        dispose();
        GUI_Start main_menu=new GUI_Start();
        main_menu.embeddedMain();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopButtonActionPerformed

    private void addVoterBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoterBackActionPerformed
        cards.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_addVoterBackActionPerformed

    private void addCandidateBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidateBackActionPerformed
        cards.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_addCandidateBackActionPerformed

    private void editVotersBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVotersBackActionPerformed
        cards.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_editVotersBackActionPerformed

    private void editMenuVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuVoterActionPerformed
        cards.show(mainPanel, "editVoter");
        
        String[] names = {"First name", "Last name", "Email", "Password", "Date of Birth", "State"};
        
        voterTableModel = new DefaultTableModel(admin.getAllVoters(), names){
        
        /** Making the rows uneditable so that we can't modify the information */ 
        @Override
        public boolean isCellEditable(int row, int column){  
          return false;  
        }
        };

        editVotersTable.setModel(voterTableModel);
        editVotersTable.getTableHeader().setReorderingAllowed(false);
        editVotersTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent event) {
            int row=editVotersTable.getSelectedRow();
            if (row!=-1){
                editVoterFirstName.setText((String)editVotersTable.getValueAt(row, 0));
                editVoterLastName.setText((String)editVotersTable.getValueAt(row, 1));
                editVoterEmail.setText((String)editVotersTable.getValueAt(row, 2));
                editVoterPassword.setText((String)editVotersTable.getValueAt(row, 3));
                editVoterDate.setText((String)editVotersTable.getValueAt(row, 4));
                jComboBox3.getModel().setSelectedItem((String)editVotersTable.getValueAt(row, 5));
            }   
        }
    });
        
        if (editVotersEditPanel.isVisible())
           editInvisible(editVotersEditPanel, editVotersDelete);

    }//GEN-LAST:event_editMenuVoterActionPerformed

    /** updates the voter table after an operation */
    private void updateVoterTable(DefaultTableModel tModel, JTable table){
        String[] names = {"First name", "Last name", "Email", "Password", "Date of Birth", "State"};
        tModel.setDataVector(admin.getAllVoters(), names);
        table.updateUI();
    }
    
    private void editVoterFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVoterFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editVoterFirstNameActionPerformed

    private void editVoterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVoterDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editVoterDateActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void editVotersEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVotersEditActionPerformed
       
       if (editVotersTable.getSelectedRow()!=-1)
           if (editVotersEditPanel.isVisible())
                 editInvisible(editVotersEditPanel, editVotersDelete);
           else
                 editVisible(editVotersEditPanel, editVotersDelete);
       else 
           JOptionPane.showMessageDialog(null, "You have to select a row before editing" , this.getTitle(), 1 );
    }//GEN-LAST:event_editVotersEditActionPerformed

    private void editVotersDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVotersDeleteActionPerformed
        int row=editVotersTable.getSelectedRow();
        if (row!=-1)
        {
            String firstName = (String) editVotersTable.getValueAt(row, 0);
                String lastName = (String) editVotersTable.getValueAt(row, 1);
                int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + firstName + " " + lastName + " from the database ?", this.getTitle(), JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    if (admin.removeUser((String) editVotersTable.getValueAt(row, 2)))
                    {
                        JOptionPane.showMessageDialog(null, "You have successfully removed " + firstName + " " + lastName + " from the database" , this.getTitle(), 1 );
                        updateVoterTable(voterTableModel, editVotersTable);
                        
                    }
                    else
                        JOptionPane.showMessageDialog(null, firstName + " " + lastName + " has not been deleted from the database due to an error" , this.getTitle(), 1 );
                } 
        }
        else 
           JOptionPane.showMessageDialog(null, "You have to select a row before deleting" , this.getTitle(), 1 );
    }//GEN-LAST:event_editVotersDeleteActionPerformed

    private void editVotersEditOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVotersEditOKActionPerformed
                   
           if (admin.modifyVoter(new Voter(editVoterEmail.getText(), editVoterPassword.getText(), convertSQLtoGregorian(editVoterDate.getText()), editVoterFirstName.getText(), 
                   editVoterLastName.getText(), (String)jComboBox3.getModel().getSelectedItem(), null) , (String)editVotersTable.getValueAt(editVotersTable.getSelectedRow(), 2)))
           {
               JOptionPane.showMessageDialog(null, "Informations successfully edited" , this.getTitle(), 1 );
               updateVoterTable(voterTableModel, editVotersTable);
               editInvisible(editVotersEditPanel, editVotersDelete);
           }
           else
               JOptionPane.showMessageDialog(null, "A problem occured. Your modification was not taken into account." , this.getTitle(), 1 );
    }//GEN-LAST:event_editVotersEditOKActionPerformed
    
    /** Set a panel to visible and enabled, and put a button to disabled
     * @param edit
     * @param delete */
    public void editVisible(JPanel edit, JButton delete){
        edit.setVisible(true);
        edit.setEnabled(true);
        delete.setEnabled(false);
    }
    
    /** Set a panel to invisible and disabled, and put a button to enabled
     * @param edit
     * @param delete */
    public void editInvisible(JPanel edit, JButton delete){
        edit.setVisible(false);
        edit.setEnabled(false);
        delete.setEnabled(true);
    }
    
    public boolean isCellEditable(int row,int col){
        return false;
    } 

    public void embeddedMain() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton addCandidateBack;
    private javax.swing.JButton addCandidateButton;
    private javax.swing.JLabel addCandidateCaption;
    private javax.swing.JFormattedTextField addCandidateDate;
    private javax.swing.JTextField addCandidateDescription;
    private javax.swing.JTextField addCandidateEmail;
    private javax.swing.JTextField addCandidateFirstName;
    private javax.swing.JTextField addCandidateLastName;
    private javax.swing.JPanel addCandidatePanel;
    private javax.swing.JPasswordField addCandidatePassword;
    private javax.swing.JLabel addCandidateText;
    private javax.swing.JPanel addCandidateTextPanel;
    private javax.swing.JButton addVoterBack;
    private javax.swing.JButton addVoterButton;
    private javax.swing.JLabel addVoterCaption;
    private javax.swing.JFormattedTextField addVoterDate;
    private javax.swing.JTextField addVoterEmail;
    private javax.swing.JTextField addVoterFirstName;
    private javax.swing.JTextField addVoterLastName;
    private javax.swing.JPanel addVoterPanel;
    private javax.swing.JPasswordField addVoterPassword;
    private javax.swing.JLabel addVoterText;
    private javax.swing.JPanel addVoterTextPanel;
    private javax.swing.JMenuItem blueOption;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editMenuCandidate;
    private javax.swing.JMenuItem editMenuVoter;
    private javax.swing.JFormattedTextField editVoterDate;
    private javax.swing.JTextField editVoterEmail;
    private javax.swing.JTextField editVoterFirstName;
    private javax.swing.JTextField editVoterLastName;
    private javax.swing.JTextField editVoterPassword;
    private javax.swing.JButton editVotersBack;
    private javax.swing.JLabel editVotersCaption;
    private javax.swing.JButton editVotersDelete;
    private javax.swing.JButton editVotersEdit;
    private javax.swing.JButton editVotersEditOK;
    private javax.swing.JPanel editVotersEditPanel;
    private javax.swing.JPanel editVotersPanel;
    private javax.swing.JScrollPane editVotersScrollPanel;
    private javax.swing.JTable editVotersTable;
    private javax.swing.JLabel editVotersText;
    private javax.swing.JPanel editVotersTextPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem greenOption;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel mainMenuDescription;
    private javax.swing.JLabel mainMenuText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu newMenu;
    private javax.swing.JMenuItem newMenuCandidate;
    private javax.swing.JMenuItem newMenuVoter;
    private javax.swing.JButton pauseButton;
    private javax.swing.JMenuItem redOption;
    private javax.swing.JButton settingsButton;
    private javax.swing.JPopupMenu settingsPopUp;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statusText;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel textPanel;
    private javax.swing.JLabel voteStatusText;
    // End of variables declaration//GEN-END:variables





}
