/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FileManager;
import Controller.candidateChartDisplay;
import Controller.ImageFilter;
import static View.GUI_Start.BLUE_COLOR;
import static View.GUI_Start.GREEN_COLOR;
import static View.GUI_Start.RED_COLOR;
import static View.GUI_Start.actualColor;
import Model.Candidate;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;

/**
 * GUI used by the candidates. 
 * @author rebec
 */
public class GUI_Candidate extends javax.swing.JFrame {

    private CardLayout cards;
    private Candidate admin ; 
    private FileManager f;
    private ArrayList<String[]> allCandidates ;
    
    /**
     * Creates new form GUI_Candidate
     * @param admin
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public GUI_Candidate(Candidate admin) throws SQLException, ClassNotFoundException {
        
        this.admin = admin ; 
        admin.setDataController();
        
        //analyzeChart=createVotesStackedBarChart(createStackedBarDataset(" ", " "), " ", " ");
        //analyzeChartPanel = new ChartPanel(analyzeChart);
        
        initComponents();
        
        UpdateStatusElection(admin.getStatusElection());
        
        setLocationRelativeTo(null);
        setVisible(true);
        
        allCandidates = admin.getAllCandidatesInfos();
        
        //Setting State values in the combo boxes
        for (String[] s : allCandidates)
        {
            candidatesComboBox.addItem(s[0]);
        }
        candidatesComboBox.addItem("(All)");
        
        cards = (CardLayout)mainPanel.getLayout();
        
        setImage(); 
        
        //File Manager to save users preferences
        try {
            f=new FileManager(); 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_Official.class.getName()).log(Level.SEVERE, null, ex);
        }
        changeColor(actualColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsPopUp = new javax.swing.JPopupMenu();
        redOption = new javax.swing.JMenuItem();
        greenOption = new javax.swing.JMenuItem();
        blueOption = new javax.swing.JMenuItem();
        imageChooser = new javax.swing.JFileChooser();
        leftPanel = new javax.swing.JPanel();
        SetingColorButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        main_menu = new javax.swing.JPanel();
        mainMenuDescription = new javax.swing.JLabel();
        mainMenuText = new javax.swing.JLabel();
        questionVote = new javax.swing.JLabel();
        answerVote = new javax.swing.JLabel();
        viewStatisticButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        republicText = new javax.swing.JLabel();
        colorPanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editProfileFirstName = new javax.swing.JTextField();
        editProfileLastName = new javax.swing.JTextField();
        editCandidateDate = new javax.swing.JFormattedTextField();
        editCandidateEmail = new javax.swing.JTextField();
        editCandidatePassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        goBackButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        editCandidateParty = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        changeImageButton = new javax.swing.JButton();
        viewStatsPanel = new javax.swing.JPanel();
        AnalyzeText = new javax.swing.JLabel();
        AnalyzeCaption = new javax.swing.JLabel();
        selectCandidateLabel = new javax.swing.JLabel();
        candidatesComboBox = new javax.swing.JComboBox();
        goBackButton1 = new javax.swing.JButton();
        statPanel = new javax.swing.JPanel();
        bufferPanel = new javax.swing.JPanel();
        imageRetrieved = new javax.swing.JLabel();

        settingsPopUp.setPreferredSize(new java.awt.Dimension(200, 100));
        settingsPopUp.setRequestFocusEnabled(false);

        redOption.setText("Set color to red");
        redOption.setPreferredSize(new java.awt.Dimension(313, 46));
        redOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(redOption);

        greenOption.setText("Set color to green");
        greenOption.setPreferredSize(new java.awt.Dimension(313, 46));
        greenOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(greenOption);

        blueOption.setText("Set color to blue");
        blueOption.setPreferredSize(new java.awt.Dimension(313, 46));
        blueOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueOptionActionPerformed(evt);
            }
        });
        settingsPopUp.add(blueOption);

        imageChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        imageChooser.setApproveButtonText("");
        imageChooser.setApproveButtonToolTipText("");
        imageChooser.setBackground(java.awt.Color.darkGray);
        imageChooser.setCurrentDirectory(new java.io.File("C:\\Users"));
        imageChooser.setFileFilter(new ImageFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election Simulator");
        setMinimumSize(new java.awt.Dimension(1024, 720));

        leftPanel.setBackground(new java.awt.Color(0, 102, 130));
        leftPanel.setMaximumSize(new java.awt.Dimension(180, 0));
        leftPanel.setMinimumSize(new java.awt.Dimension(180, 0));
        leftPanel.setPreferredSize(new java.awt.Dimension(180, 0));

        SetingColorButton.setBackground(new java.awt.Color(255, 255, 255));
        SetingColorButton.setForeground(new java.awt.Color(255, 255, 255));
        SetingColorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/gearIcon.png"))); // NOI18N
        SetingColorButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        SetingColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetingColorButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logoutIcon.png"))); // NOI18N
        exitButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/userIcon.png"))); // NOI18N
        profileButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(SetingColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(682, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetingColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        mainPanel.setPreferredSize(new java.awt.Dimension(844, 686));
        mainPanel.setLayout(new java.awt.CardLayout());

        main_menu.setBackground(new java.awt.Color(255, 255, 255));
        main_menu.setPreferredSize(new java.awt.Dimension(668, 686));

        mainMenuDescription.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuDescription.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        mainMenuDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuDescription.setText("Candidate Main Menu");
        mainMenuDescription.setMaximumSize(new java.awt.Dimension(268, 47));
        mainMenuDescription.setMinimumSize(new java.awt.Dimension(2, 47));
        mainMenuDescription.setPreferredSize(new java.awt.Dimension(289, 47));

        mainMenuText.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuText.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        mainMenuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuText.setText(admin.getFirstName() + " " + admin.getLastName() + ", welcome to the candidate center.");

        questionVote.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        questionVote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionVote.setText("Status of the election : ");

        answerVote.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        answerVote.setForeground(new java.awt.Color(0, 153, 51));
        answerVote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerVote.setText("Active");

        viewStatisticButton.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        viewStatisticButton.setText("View votes and compare with other canidates");
        viewStatisticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatisticButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/index.png"))); // NOI18N

        republicText.setBackground(new java.awt.Color(255, 255, 255));
        republicText.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        republicText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        republicText.setText("Republic of Moebus");

        colorPanel.setBackground(actualColor   );

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout main_menuLayout = new javax.swing.GroupLayout(main_menu);
        main_menu.setLayout(main_menuLayout);
        main_menuLayout.setHorizontalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(questionVote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(republicText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainMenuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainMenuDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(answerVote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewStatisticButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_menuLayout.setVerticalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainMenuDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuText)
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(republicText)
                .addGap(18, 18, 18)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(questionVote)
                .addGap(18, 18, 18)
                .addComponent(answerVote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(viewStatisticButton)
                .addGap(56, 56, 56))
        );

        mainPanel.add(main_menu, "mainMenu");

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.setMinimumSize(new java.awt.Dimension(844, 686));
        profilePanel.setPreferredSize(new java.awt.Dimension(844, 686));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile");

        editProfileFirstName.setText(admin.getFirstName());
        editProfileFirstName.setBorder(javax.swing.BorderFactory.createTitledBorder("First Name"));
        editProfileFirstName.setEnabled(false);
        editProfileFirstName.setMinimumSize(new java.awt.Dimension(12, 74));
        editProfileFirstName.setPreferredSize(new java.awt.Dimension(12, 74));

        editProfileLastName.setText(admin.getLastName());
        editProfileLastName.setBorder(javax.swing.BorderFactory.createTitledBorder("Last Name"));
        editProfileLastName.setEnabled(false);
        editProfileLastName.setMinimumSize(new java.awt.Dimension(12, 74));
        editProfileLastName.setPreferredSize(new java.awt.Dimension(12, 74));

        editCandidateDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Date of birth"));
        editCandidateDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        editCandidateDate.setText(admin.getDOB());
        editCandidateDate.setEnabled(false);
        editCandidateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCandidateDateActionPerformed(evt);
            }
        });

        editCandidateEmail.setText(admin.getEmail());
        editCandidateEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Email"));

        editCandidatePassword.setText(admin.getPassword());
        editCandidatePassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password"));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("If you want to modify your name, date of birth or party, please contact an official.");

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Modifications");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editCandidateParty.setText(admin.getParty());
        editCandidateParty.setBorder(javax.swing.BorderFactory.createTitledBorder("Party"));
        editCandidateParty.setEnabled(false);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        changeImageButton.setText("Change your profile picture");
        changeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeImageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editCandidateEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(editProfileFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(editProfileLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 39, Short.MAX_VALUE)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editCandidateDate, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(editCandidatePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(editCandidateParty, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(changeImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(goBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addGap(20, 20, 20))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProfileFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCandidateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProfileLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCandidateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCandidatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(editCandidateParty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(changeImageButton))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goBackButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        mainPanel.add(profilePanel, "profile");

        viewStatsPanel.setBackground(new java.awt.Color(255, 255, 255));

        AnalyzeText.setBackground(new java.awt.Color(255, 255, 255));
        AnalyzeText.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        AnalyzeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnalyzeText.setText("Analysis");

        AnalyzeCaption.setBackground(new java.awt.Color(255, 255, 255));
        AnalyzeCaption.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        AnalyzeCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnalyzeCaption.setText("Review votes under diverse circumstances");

        selectCandidateLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectCandidateLabel.setText("Select the candidate you want to compare with :");

        candidatesComboBox.setBorder(null);
        candidatesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatesComboBoxActionPerformed(evt);
            }
        });

        goBackButton1.setText("Go Back");
        goBackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButton1ActionPerformed(evt);
            }
        });

        statPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout viewStatsPanelLayout = new javax.swing.GroupLayout(viewStatsPanel);
        viewStatsPanel.setLayout(viewStatsPanelLayout);
        viewStatsPanelLayout.setHorizontalGroup(
            viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnalyzeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(viewStatsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewStatsPanelLayout.createSequentialGroup()
                        .addComponent(goBackButton1)
                        .addGap(408, 747, Short.MAX_VALUE))
                    .addGroup(viewStatsPanelLayout.createSequentialGroup()
                        .addGroup(viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(viewStatsPanelLayout.createSequentialGroup()
                                .addComponent(selectCandidateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(candidatesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
            .addComponent(AnalyzeCaption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewStatsPanelLayout.setVerticalGroup(
            viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewStatsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AnalyzeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnalyzeCaption)
                .addGap(34, 34, 34)
                .addGroup(viewStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCandidateLabel)
                    .addComponent(candidatesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(goBackButton1)
                .addContainerGap())
        );

        mainPanel.add(viewStatsPanel, "statsPanel");

        imageRetrieved.setBackground(new java.awt.Color(255, 255, 255));
        imageRetrieved.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        imageRetrieved.setForeground(new java.awt.Color(50, 50, 50));
        imageRetrieved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageRetrieved.setText("Select an image");

        javax.swing.GroupLayout bufferPanelLayout = new javax.swing.GroupLayout(bufferPanel);
        bufferPanel.setLayout(bufferPanelLayout);
        bufferPanelLayout.setHorizontalGroup(
            bufferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
            .addGroup(bufferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bufferPanelLayout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(imageRetrieved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(166, 166, 166)))
        );
        bufferPanelLayout.setVerticalGroup(
            bufferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(bufferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bufferPanelLayout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(imageRetrieved, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );

        mainPanel.add(bufferPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** 
     * Update the output of the status of the election. 
     * @param status
     * @return 
     */
    private void UpdateStatusElection(String status){
        switch(status)
        {
            case "Active" :
                answerVote.setForeground(GREEN_COLOR);
                answerVote.setText(status);
                break;
            case "Paused" :
                answerVote.setForeground(BLUE_COLOR);
                answerVote.setText(status);
                break;
            case "Done":
                answerVote.setForeground(RED_COLOR);
                answerVote.setText(status);
                break;
            default :
                answerVote.setText("Done");
                break;
        }
    }
    
    /**
     * Set the image of the candidate
     */
    private void setImage()
    {
        byte[] myImage = admin.getImage();
        if (myImage!=null)
        {
            ImageIcon image = new ImageIcon(myImage);
            imageLabel.setText("");
            imageLabel.setIcon(image);
        }
        else
        {
            imageLabel.setText("There is no picture available.");
            imageLabel.setIcon(null);
        }
    }
    
    private void SetingColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetingColorButtonActionPerformed
        settingsPopUp.show(this, SetingColorButton.getX(), SetingColorButton.getY()-settingsPopUp.getHeight()/2-2);
    }//GEN-LAST:event_SetingColorButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
        GUI_Start mainMenu;
        try {
            mainMenu = new GUI_Start();
            mainMenu.embeddedMain();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GUI_Official.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    
    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        cards.show(mainPanel, "profile");
    }//GEN-LAST:event_profileButtonActionPerformed

    /**
     * Change the color background of the layout
     * @param c 
     */
    private void changeColor(Color c){
        leftPanel.setBackground(c);
        f.saveColor(c);
    }
    
    private void redOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redOptionActionPerformed
        actualColor=RED_COLOR;
        changeColor(actualColor);
    }//GEN-LAST:event_redOptionActionPerformed

    private void greenOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenOptionActionPerformed
        actualColor=GREEN_COLOR;
        changeColor(actualColor);
    }//GEN-LAST:event_greenOptionActionPerformed

    private void blueOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueOptionActionPerformed
        actualColor=BLUE_COLOR;
        changeColor(actualColor);
    }//GEN-LAST:event_blueOptionActionPerformed

    private void viewStatisticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatisticButtonActionPerformed
        cards.show(mainPanel, "statsPanel");
    }//GEN-LAST:event_viewStatisticButtonActionPerformed

    private void editCandidateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCandidateDateActionPerformed

    }//GEN-LAST:event_editCandidateDateActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        cards.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String [] infosModif = new String[2] ; 
        infosModif[0] = editCandidateEmail.getText(); 
        infosModif[1] = editCandidatePassword.getText(); 
        if(infosModif[0].equals("") || infosModif[1].equals(""))
            JOptionPane.showMessageDialog(null, "The new email or password enter is empty, please complet it to be able to modify your profil." , this.getTitle(), 1 );
        else if(admin.updateProfile(infosModif))
            JOptionPane.showMessageDialog(null, "Informations successfully edited" , this.getTitle(), 1 );
        else 
            JOptionPane.showMessageDialog(null, "A problem occured. Your modification was not taken into account." , this.getTitle(), 1 );
    }//GEN-LAST:event_saveButtonActionPerformed

    private void goBackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButton1ActionPerformed
        cards.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_goBackButton1ActionPerformed

    /**
     * Update a Panel following an update of ChartPanel
     * @param board
     * @param chart 
     */
    private void loardChart(JPanel board, ChartPanel chart)
    {
        board.removeAll();
        BorderLayout b = (BorderLayout) board.getLayout(); 
        board.add(chart, b.CENTER); 
        board.validate();
    }
    
    private void candidatesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidatesComboBoxActionPerformed
        String nameCompare = (String) candidatesComboBox.getSelectedItem();
        if(nameCompare.equals("(All)"))
        {
            candidateChartDisplay chartDisplayer = new candidateChartDisplay(admin);
            loardChart(statPanel, new ChartPanel(chartDisplayer.createAllStackedBarChart(chartDisplayer.createAllStackedBarDataset())));
        }
        else
        {
            System.out.print("ok");
            String emailCompare = allCandidates.get(candidatesComboBox.getSelectedIndex())[1];
            candidateChartDisplay chartDisplayer = new candidateChartDisplay(admin); 
            loardChart(statPanel, new ChartPanel(chartDisplayer.createVotesStackedBarChart(chartDisplayer.createStackedBarDataset(nameCompare, emailCompare), nameCompare, emailCompare)));
        }
    }//GEN-LAST:event_candidatesComboBoxActionPerformed

    private void changeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeImageButtonActionPerformed
        int returnVal = imageChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = imageChooser.getSelectedFile();
            ImageIcon myImage = new ImageIcon(f.toString());
            ImageIcon scaledImage = new ImageIcon(myImage.getImage().getScaledInstance(imageRetrieved.getWidth(),imageRetrieved.getHeight() , java.awt.Image.SCALE_SMOOTH));
            imageLabel.setText("");
            imageLabel.setIcon(scaledImage);
            
            try {
                    if (imageLabel.getIcon()!=null) //If there's an image
                        if (!admin.uploadImage(imageChooser.getSelectedFile())) //Then try to upload it
                            JOptionPane.showMessageDialog(null, "Problem uploading the image" , this.getTitle(), 1 );       
            } catch (IOException ex) {
                    Logger.getLogger(GUI_Official.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        else 
            JOptionPane.showMessageDialog(null, "Couldn't access the file." , this.getTitle(), 1 );
    }//GEN-LAST:event_changeImageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void embeddedMain() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnalyzeCaption;
    private javax.swing.JLabel AnalyzeText;
    private javax.swing.JButton SetingColorButton;
    private javax.swing.JLabel answerVote;
    private javax.swing.JMenuItem blueOption;
    private javax.swing.JPanel bufferPanel;
    private javax.swing.JComboBox candidatesComboBox;
    private javax.swing.JButton changeImageButton;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JFormattedTextField editCandidateDate;
    private javax.swing.JTextField editCandidateEmail;
    private javax.swing.JTextField editCandidateParty;
    private javax.swing.JTextField editCandidatePassword;
    private javax.swing.JTextField editProfileFirstName;
    private javax.swing.JTextField editProfileLastName;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton goBackButton1;
    private javax.swing.JMenuItem greenOption;
    private javax.swing.JFileChooser imageChooser;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imageRetrieved;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel mainMenuDescription;
    private javax.swing.JLabel mainMenuText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel main_menu;
    private javax.swing.JButton profileButton;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel questionVote;
    private javax.swing.JMenuItem redOption;
    private javax.swing.JLabel republicText;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel selectCandidateLabel;
    private javax.swing.JPopupMenu settingsPopUp;
    private javax.swing.JPanel statPanel;
    private javax.swing.JButton viewStatisticButton;
    private javax.swing.JPanel viewStatsPanel;
    // End of variables declaration//GEN-END:variables
}
